server:
  port: 8090  # 应用服务的 WEB 访问端口
  servlet:
    context-path: /api  # 应用服务的 WEB 访问路径

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/caiapi  # MySQL 数据库连接 URL
    username: root  # 数据库用户名
    password: root  # 数据库密码
    driver-class-name: com.mysql.cj.jdbc.Driver  # JDBC 驱动类

  jpa:
    hibernate:
      ddl-auto: update  # 自动更新数据库表结构
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl  # 使用标准命名策略，不转换驼峰命名
    show-sql: true  # 控制台打印 SQL 语句

caiapi:
  client:
    access-key: mdo
    secret-key: 123456
