server:
  port: 8123

spring:
  cloud:
    gateway:
      routes:
        - id: api_route
          uri: http://localhost:8090
          predicates:
            - Path=/api/**

dubbo:
  application:
    name: dubbo-springboot-demo-provider
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://localhost:8848